export const GET_LIST_INGREDIENTS_REQUEST = 'GET_LIST_INGREDIENTS_REQUEST';
export const GET_LIST_INGREDIENTS_SUCCESS = 'GET_LIST_INGREDIENTS_SUCCESS';
export const GET_LIST_INGREDIENTS_FAILED = 'GET_LIST_INGREDIENTS_FAILED';

export const CHANGE_CURRENT_ORDER_INGREDIENTS = 'CHANGE_CURRENT_ORDER_INGREDIENTS';
export const ADD_CURRENT_ORDER_INGREDIENTS = 'ADD_CURRENT_ORDER_INGREDIENTS';
export const DELETE_CURRENT_ORDER_INGREDIENTS = 'DELETE_CURRENT_ORDER_INGREDIENTS';

export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT';
export const DELETE_CURRENT_INGREDIENT = 'DELETE_CURRENT_INGREDIENT';

export const GET_ORDER_NUMBER_REQUEST = 'GET_ORDER_NUMBER_REQUEST';
export const GET_ORDER_NUMBER_SUCCESS = 'GET_ORDER_NUMBER_SUCCESS';
export const GET_ORDER_NUMBER_FAILED = 'GET_ORDER_NUMBER_FAILED';
export const DELETE_ORDER_NUMBER = 'DELETE_ORDER_NUMBER';
export const ADD_DRAG_INGREDIENT = 'ADD_DRAG_INGREDIENT';

export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const RESET_EMAIL_SUCCESS = 'RESET_EMAIL_SUCCESS';
export const RESET_EMAIL_FAILED = 'RESET_EMAIL_FAILED';

export const ORDER_PRICE = 'ORDER_PRICE';

export const SET_MODAL_STATUS = 'SET_MODAL_STATUS';

export const SET_USER_REGISTRY = 'SET_USER_REGISTRY';
export const CLEAN_USER = 'CLEAN_USER';
export const USER_ERROR = 'USER_ERROR';
export const SET_USER = 'SET_USER';
export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const AUTH_USER = 'AUTH_USER';
export const USER_REQUEST = 'USER_REQUEST';
export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';